"""core curriculum and student record schema

Revision ID: 0002_core_schema
Revises: 0001_enable_pgvector
Create Date: 2026-07-30 09:06:36.333049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders embedding columns as pgvector.sqlalchemy.Vector(...), so the
# name has to be in scope in every revision that touches document_chunks.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0002_core_schema'
down_revision: Union[str, Sequence[str], None] = '0001_enable_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_code', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=96), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('credits > 0', name='ck_courses_credits_positive'),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('grading_scale',
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('grade_points', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('earns_credit', sa.Boolean(), nullable=False),
    sa.Column('included_in_gpa', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(included_in_gpa AND grade_points IS NOT NULL) OR (NOT included_in_gpa AND grade_points IS NULL)', name='ck_grading_points_match_gpa_inclusion'),
    sa.CheckConstraint('grade_points IS NULL OR (grade_points >= 0 AND grade_points <= 4)', name='ck_grading_points_range'),
    sa.PrimaryKeyConstraint('grade')
    )
    op.create_table('programs',
    sa.Column('program_code', sa.String(length=16), nullable=False),
    sa.Column('program_name', sa.String(length=64), nullable=False),
    sa.Column('total_credits_required', sa.Integer(), nullable=False),
    sa.CheckConstraint('total_credits_required > 0', name='ck_programs_total_credits_positive'),
    sa.PrimaryKeyConstraint('program_code'),
    sa.UniqueConstraint('program_name')
    )
    op.create_table('terms',
    sa.Column('term_code', sa.String(length=8), nullable=False),
    sa.Column('term_name', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_terms_dates_ordered'),
    sa.PrimaryKeyConstraint('term_code'),
    sa.UniqueConstraint('term_name')
    )
    op.create_table('class_schedule',
    sa.Column('term_code', sa.String(length=8), nullable=False),
    sa.Column('course_code', sa.String(length=12), nullable=False),
    sa.Column('days', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=24), nullable=False),
    sa.Column('instructor', sa.String(length=64), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_schedule_times_ordered'),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ),
    sa.ForeignKeyConstraint(['term_code'], ['terms.term_code'], ),
    sa.PrimaryKeyConstraint('term_code', 'course_code')
    )
    op.create_table('course_prerequisites',
    sa.Column('course_code', sa.String(length=12), nullable=False),
    sa.Column('prerequisite_course_code', sa.String(length=12), nullable=False),
    sa.CheckConstraint('course_code <> prerequisite_course_code', name='ck_prereq_not_self'),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_code'], ['courses.course_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_code', 'prerequisite_course_code')
    )
    op.create_table('program_requirement_categories',
    sa.Column('category_id', sa.String(length=24), nullable=False),
    sa.Column('program_code', sa.String(length=16), nullable=False),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.Column('credits_required', sa.Integer(), nullable=False),
    sa.Column('selection_rule', sa.String(length=8), nullable=False),
    sa.Column('courses_required', sa.Integer(), nullable=True),
    sa.CheckConstraint("(selection_rule = 'ALL' AND courses_required IS NULL) OR (selection_rule = 'ANY_N' AND courses_required > 0)", name='ck_category_courses_required_matches_rule'),
    sa.CheckConstraint("selection_rule IN ('ALL', 'ANY_N')", name='ck_category_selection_rule'),
    sa.CheckConstraint('credits_required > 0', name='ck_category_credits_positive'),
    sa.ForeignKeyConstraint(['program_code'], ['programs.program_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('program_code', 'category_name', name='uq_category_per_program')
    )
    op.create_table('students',
    sa.Column('student_id', sa.String(length=12), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('program_code', sa.String(length=16), nullable=False),
    sa.Column('entry_term', sa.String(length=8), nullable=False),
    sa.Column('expected_graduation_term', sa.String(length=8), nullable=False),
    sa.Column('academic_status', sa.String(length=24), nullable=False),
    sa.Column('advisor_name', sa.String(length=64), nullable=False),
    sa.Column('scenario_note', sa.Text(), nullable=True),
    sa.CheckConstraint("academic_status IN ('Good standing', 'Academic probation', 'Academic dismissal')", name='ck_students_academic_status'),
    sa.ForeignKeyConstraint(['entry_term'], ['terms.term_code'], ),
    sa.ForeignKeyConstraint(['program_code'], ['programs.program_code'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category_courses',
    sa.Column('category_id', sa.String(length=24), nullable=False),
    sa.Column('course_code', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['program_requirement_categories.category_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'course_code')
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.String(length=12), nullable=False),
    sa.Column('term_code', sa.String(length=8), nullable=False),
    sa.Column('course_code', sa.String(length=12), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("(status = 'In progress' AND grade IS NULL) OR (status = 'Completed' AND grade IS NOT NULL)", name='ck_enrollments_grade_matches_status'),
    sa.CheckConstraint("status IN ('Completed', 'In progress')", name='ck_enrollments_status'),
    sa.CheckConstraint('credits > 0', name='ck_enrollments_credits_positive'),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ),
    sa.ForeignKeyConstraint(['grade'], ['grading_scale.grade'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_code'], ['terms.term_code'], ),
    sa.PrimaryKeyConstraint('student_id', 'term_code', 'course_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('category_courses')
    op.drop_table('students')
    op.drop_table('program_requirement_categories')
    op.drop_table('course_prerequisites')
    op.drop_table('class_schedule')
    op.drop_table('terms')
    op.drop_table('programs')
    op.drop_table('grading_scale')
    op.drop_table('courses')
    # ### end Alembic commands ###
