"""per-category minimum grade points for Major Core C- gate

Revision ID: 0003_category_min_grade
Revises: 0002_core_schema
Create Date: 2026-07-30 09:13:22.359772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders embedding columns as pgvector.sqlalchemy.Vector(...), so the
# name has to be in scope in every revision that touches document_chunks.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0003_category_min_grade'
down_revision: Union[str, Sequence[str], None] = '0002_core_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_requirement_categories', sa.Column('min_grade_points', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_requirement_categories', 'min_grade_points')
    # ### end Alembic commands ###
