"""documents and document_chunks for retrieval

Hand-written rather than autogenerated: Docker was not running when this phase
started, so there was no live database to compare the models against. The
`--autogenerate` diff is still the check -- running it against an upgraded
database must produce an empty revision.

Revision ID: 0004_document_retrieval
Revises: 0003_category_min_grade
Create Date: 2026-08-01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders embedding columns as pgvector.sqlalchemy.Vector(...), so the
# name has to be in scope in every revision that touches document_chunks.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0004_document_retrieval'
down_revision: Union[str, Sequence[str], None] = '0003_category_min_grade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'documents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('filename', sa.String(length=128), nullable=False),
        sa.Column('title', sa.String(length=128), nullable=False),
        sa.Column(
            'uploaded_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('sha256', sa.String(length=64), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'ingesting', 'ready', 'failed')",
            name='ck_documents_status',
        ),
        sa.CheckConstraint(
            'page_count IS NULL OR page_count > 0', name='ck_documents_page_count'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('filename'),
    )
    op.create_table(
        'document_chunks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        # 1536 is text-embedding-3-small at its default size (CLAUDE.md section 3).
        # Changing the embedding model means a migration here plus a re-embed --
        # cheap at eleven pages, which is why the decision is not a one-way door.
        sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
        sa.Column('chunk_kind', sa.String(length=16), nullable=False),
        sa.Column('section_ref', sa.String(length=32), nullable=True),
        sa.Column('section_title', sa.String(length=128), nullable=True),
        sa.Column('page', sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "chunk_kind IN ('course', 'program', 'policy', 'overview')",
            name='ck_chunk_kind',
        ),
        sa.CheckConstraint('page IS NULL OR page > 0', name='ck_chunk_page_positive'),
        sa.CheckConstraint('length(content) > 0', name='ck_chunk_content_not_empty'),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_position'),
    )
    op.create_index('ix_chunks_document', 'document_chunks', ['document_id'])
    # Deliberately no index on `embedding`. At ~70 chunks an exact sequential
    # scan is faster than an approximate index and, unlike IVFFlat/HNSW, cannot
    # miss the true nearest neighbour. Revisit when the corpus is large enough
    # for a query plan to justify it.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('documents')
