"""student_sessions, assistant_settings, conversations and messages

The Phase 4 agent layer. Also seeds the single `assistant_settings` row, because
a table constrained to exactly one row that has zero rows is not a valid state --
every chat request reads it, and "no settings configured" would be a startup
failure with no way to fix it through the app.

Hand-written rather than autogenerated (no live database available at the time);
`--autogenerate` against an upgraded database must produce an empty revision.

Revision ID: 0005_agent_layer
Revises: 0004_document_retrieval
Create Date: 2026-08-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Autogenerate renders embedding columns as pgvector.sqlalchemy.Vector(...), so the
# name has to be in scope in every revision that touches document_chunks.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0005_agent_layer'
down_revision: Union[str, Sequence[str], None] = '0004_document_retrieval'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'student_sessions',
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('student_id', sa.String(length=12), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            'expires_at > created_at', name='ck_session_expiry_after_start'
        ),
        sa.ForeignKeyConstraint(
            ['student_id'], ['students.student_id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('token_hash'),
    )
    op.create_index('ix_sessions_student', 'student_sessions', ['student_id'])

    op.create_table(
        'assistant_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tone', sa.String(length=16), nullable=False),
        sa.Column('model_name', sa.String(length=64), nullable=False),
        sa.Column('response_length', sa.String(length=16), nullable=False),
        sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('id = 1', name='ck_settings_single_row'),
        sa.CheckConstraint(
            "tone IN ('friendly', 'neutral', 'formal')", name='ck_settings_tone'
        ),
        sa.CheckConstraint(
            "response_length IN ('brief', 'standard', 'detailed')",
            name='ck_settings_length',
        ),
        sa.CheckConstraint(
            'temperature >= 0 AND temperature <= 2', name='ck_settings_temperature'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # Seeded here, not by application code. The single-row CHECK means the app
    # cannot bootstrap it concurrently without a race, and a chat request that
    # has to create its own configuration before it can answer is a worse first
    # experience than one that finds it already there.
    #
    # Defaults: openai:gpt-5-mini because OPENAI_API_KEY is already mandatory for
    # embeddings (CLAUDE.md section 3), so one key runs the whole system. The
    # model is admin-configurable precisely so this is not a commitment --
    # switching to anthropic:claude-* is an UPDATE plus a second key.
    op.execute(
        """
        INSERT INTO assistant_settings
            (id, tone, model_name, response_length, temperature)
        VALUES
            (1, 'friendly', 'openai:gpt-5-mini', 'standard', 0.20)
        """
    )

    op.create_table(
        'conversations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.String(length=12), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['student_id'], ['students.student_id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_conversations_student', 'conversations', ['student_id'])

    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=16), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        # The serialised PydanticAI ModelMessage, replayed as history on the next
        # turn. JSONB rather than Text so the admin panel can query into it later
        # without a second parse.
        sa.Column('model_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_messages_role'),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_messages_conversation', 'messages', ['conversation_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_student', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('assistant_settings')
    op.drop_index('ix_sessions_student', table_name='student_sessions')
    op.drop_table('student_sessions')
