"""advisor_appointments

The Phase 5 human-in-the-loop table. Note what is *not* here: a 'proposed'
status. A proposal is never written -- the tool returns it and stops -- so a row
in this table always means a student explicitly said yes in a later turn.

Hand-written rather than autogenerated (no live database available at the time);
`--autogenerate` against an upgraded database must produce an empty revision.

Revision ID: 0006_advisor_appointments
Revises: 0005_agent_layer
Create Date: 2026-08-02

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders embedding columns as pgvector.sqlalchemy.Vector(...), so the
# name has to be in scope in every revision that touches document_chunks.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0006_advisor_appointments'
down_revision: Union[str, Sequence[str], None] = '0005_agent_layer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'advisor_appointments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('student_id', sa.String(length=12), nullable=False),
        sa.Column('advisor_name', sa.String(length=64), nullable=False),
        sa.Column('proposed_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('confirmed', 'cancelled')", name='ck_appointment_status'
        ),
        sa.ForeignKeyConstraint(
            ['student_id'], ['students.student_id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'student_id', 'proposed_time', name='uq_appointment_student_slot'
        ),
    )
    op.create_index('ix_appointments_student', 'advisor_appointments', ['student_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_appointments_student', table_name='advisor_appointments')
    op.drop_table('advisor_appointments')
