"""admin_sessions

The Phase 6 admin login. A separate table from `student_sessions` rather than a
nullable owner column on a shared one -- see the model docstring for why.

Hand-written rather than autogenerated (no live database available at the time);
`--autogenerate` against an upgraded database must produce an empty revision.

Revision ID: 0007_admin_sessions
Revises: 0006_advisor_appointments
Create Date: 2026-08-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders embedding columns as pgvector.sqlalchemy.Vector(...), so the
# name has to be in scope in every revision that touches document_chunks.
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0007_admin_sessions'
down_revision: Union[str, Sequence[str], None] = '0006_advisor_appointments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'admin_sessions',
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            'expires_at > created_at', name='ck_admin_session_expiry_after_start'
        ),
        sa.PrimaryKeyConstraint('token_hash'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('admin_sessions')
